name = "Pylustrator"
uuid = "e5bec534-b9b5-4198-8c6c-e8157877c5d1"
authors = ["S J Palmer <samuelpalmer94@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
julia = "1"
MacroTools = "0.5"
PyCall = "1"
PyPlot = "2"
